version: '2.0'
services:
  Peer2Profit:
    build:
      context: .
      dockerfile: Dockerfile
    image: enwaiax/peer2profit
    restart: unless-stopped
    environment: 
      - email=dahuomao@gmail.com
    command: 
      - "/app/p2pclient"
      - "-l"
      - "dahuomao@gmail.com"
